### PR TITLE
add milopy tutorial

### PR DESCRIPTION
**Pull request by xinyuejohn**
Adapted original milopy tutorial notebook.

### CODE REVIEW

**Comment by Zethson** [comment]
@emdann what do you think? Is this going into the right direction?

**Comment by emdann** [comment]
Great work here! I've tested the tutorial and main functions and left comments here and in https://github.com/theislab/pertpy/pull/165.

In general, I think the Milo tutorial needs to be more extensive, demonstrating how to use contrasts in `da_nhoods` for different types of comparisons and showcasing more of the utility and plotting functions. If that's ok with you I would be happy to give a go at re-writing the tutorial, and this might also allow me to stress-test the new implementation a bit more thoroughly.

**Comment by Zethson** [comment]
@emdann would be amazing if you could extend the tutorial. Please feel free to have a go at it!

**Comment by xinyuejohn** [comment]
<p>Exactly, I also found this issue. </p>

---

 <a href='https://app.reviewnb.com/theislab/pertpy-tutorials/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by emdann** [comment]
@Zethson do you have anything against using a different dataset for this tutorial? e.g. one of the disease datasets available via [extended HLCA](https://zenodo.org/record/6337966/#.Y20e5OzP23I) or COVID19 Stephenson dataset (I have a subsampled version on figshare).

**Comment by Zethson** [comment]
@emdann No, please go ahead! Ideally it will then also be available as a pertpy dataloader. If you could submit a quick and dirty PR for this then it would be even better. But also fine without.

**Comment by emdann** [comment]
sure, makes sense!

**Comment by emdann** [comment]
@Zethson  I don't have rights to push to `origin/feature/milopy`. What's the best way to push my changes to this PR? Should I make a new PR from my fork?

**Comment by Zethson** [comment]
Check Github mails pls

**Comment by emdann** [comment]
Draft for revamped tutorial is here! While prepping this I found some minor issues with some functions, I will post a separate issue on pertpy.

**Comment by Zethson** [comment]
@emdann do you want me to have a look at it already?

Yes, please do. Just ping @xinyuejohn then and he'll surely take care of it.

Thank you!

**Comment by emdann** [comment]
Yes pls review

**Comment by Zethson** [comment]
Just very minor comments. Think this is def good enough for a nice tutorial.

Feel free to merge after you're happy with it. I'll add it to the rendered docs then.

**Pull request merged**
