### PR TITLE
Add perturbation space

### PR DESCRIPTION
**Pull request by Zethson**

### CODE REVIEW

**Comment by Lilly-May** [comment]
I've completed the tutorial with the Norman dataset, and I'm quite happy with the results. The perturbation spaces appear to effectively capture the individual effects of the perturbations, as the embedded perturbations cluster nicely in accordance with the gene programs.
I would appreciate feedback on how well everything is explained and if there are any additional functionalities that should be included in the tutorial.

**Comment by Lilly-May** [comment]
<p>I agree, I changed it to <code>found_programme</code></p>

---

 <a href='https://app.reviewnb.com/theislab/pertpy-tutorials/pull/17/discussion/#comment-1872504730'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>How about changing the first sentence to this:</p><blockquote>pertpy delineates between two fundamental domains to embed and analyze data: the "cell space" and the "perturbation space"</blockquote>

---

 <a href='https://app.reviewnb.com/theislab/pertpy-tutorials/pull/17/discussion/#comment-1872504725'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>Yes, I think that's a good idea!</p>

---

 <a href='https://app.reviewnb.com/theislab/pertpy-tutorials/pull/17/discussion/#comment-1872504740'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>Yes, I thought if someone does not want to follow the entire tutorial but only parts of it, it might be convenient to have everything (including the generation of objects) in one place. But I agree that it is quite redundant. Should we delete it?</p>

---

 <a href='https://app.reviewnb.com/theislab/pertpy-tutorials/pull/17/discussion/#comment-1872504745'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Zethson** [comment]
<p>I'd delete it</p>

---

 <a href='https://app.reviewnb.com/theislab/pertpy-tutorials/pull/17/discussion/#comment-1872504745'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>It's not necessary, we can omit that.</p>

---

 <a href='https://app.reviewnb.com/theislab/pertpy-tutorials/pull/17/discussion/#comment-1872504750'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
