### PR TITLE
Add preprint use case tutorials

### PR DESCRIPTION
**Pull request by Lilly-May**
This PR adds the three use cases from the pertpy preprint to the tutorials. I created a separate notebook for each of the Norman, McFarland, and Zhang use cases. For the Zhang use case, the Dialogue section is still missing. I’ll add that once this PR is merged, as I need to run it on the cluster.

### CODE REVIEW

**Comment by Lilly-May** [comment]
<p>I added:</p><blockquote>Overall, this tutorial demonstrates how to use pertpy to derive insights into perturbation responses in a complex dataset comprising various cell lines and drugs, with the goal of better understanding the molecular mechanisms underlying drug responses and how they vary across cell lines.</blockquote>

---

 <a href='https://app.reviewnb.com/scverse/pertpy-tutorials/pull/48/discussion/#comment-2379536381'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>Done!</p>

---

 <a href='https://app.reviewnb.com/scverse/pertpy-tutorials/pull/48/discussion/#comment-2379536407'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>Yes, true - I deleted it.</p>

---

 <a href='https://app.reviewnb.com/scverse/pertpy-tutorials/pull/48/discussion/#comment-2379536436'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>I changed the paragraph to:</p><blockquote>Datasets often come with metadata that can enable more detailed analyses, as those presented in this tutorial. However, the extent of metadata can vary greatly between datasets, and each dataset usually has its own metadata format. To address this, databases that allow for standardized metadata annotation exist. Pertpy offers multiple metadata classes to query these databases and annotate your data. Here, we will use the <code>CellLine</code> and <code>Moa</code> classes to annotate the cell lines and mechanisms of action (MOA) of the drugs, respectively.</blockquote>

---

 <a href='https://app.reviewnb.com/scverse/pertpy-tutorials/pull/48/discussion/#comment-2379536462'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>Yes, if the <code>reference_id</code> parameter is not set, <code>DepMap_ID</code> is used by default. The warning you're referencing belongs to the one in the line above. Personally, I would remove all <code>\n</code> characters from the warning so that the formatting is cleaner when printed. What do you think?</p>

---

 <a href='https://app.reviewnb.com/scverse/pertpy-tutorials/pull/48/discussion/#comment-2379536495'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>I've added one.</p>

---

 <a href='https://app.reviewnb.com/scverse/pertpy-tutorials/pull/48/discussion/#comment-2379536526'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Zethson** [comment]
<p>Yeah so removing the line breaks helps. But I think that the message "ensure that it's available" should not written in the first place. The code should just check whether this column is inside the object and if not -&gt; error with a message. Else, don't print this useless logging message.</p><p> </p><p>In general, the UX is suboptimal here. There should simply be better inference of parameters and just defaults.</p>

---

 <a href='https://app.reviewnb.com/scverse/pertpy-tutorials/pull/48/discussion/#comment-2379536495'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>This is what is done - here the respective section in the code.</p><p> </p>

<pre class="ql-syntax" spellcheck="false">if sum(adata.obsm[metadata_key].columns != adata.var.index.values) &gt; 0:
    logger.warning(
        "Column name of metadata is not the same as the index of adata.var. Ensure that the genes are in the same order."
    )
</pre><p> </p><p>So, we could either just change the warning and make the message clearer or we raise an Error and let the method fail when this happens?</p>

---

 <a href='https://app.reviewnb.com/scverse/pertpy-tutorials/pull/48/discussion/#comment-2379536548'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Zethson** [comment]
<p>Yeah if it's critical for the usage of the function it should error. Else we should clarify the effect that this has. If it has no effect at all -&gt; remove warning.</p>

---

 <a href='https://app.reviewnb.com/scverse/pertpy-tutorials/pull/48/discussion/#comment-2379536548'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>Yes, we can - thanks for noting that! I changed it.</p>

---

 <a href='https://app.reviewnb.com/scverse/pertpy-tutorials/pull/48/discussion/#comment-2379536568'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>I added:</p><blockquote>Pertpy facilitates the preprocessing of perturbation datasets, for example, by removing confounding effects using Mixscape. We can then use the identified perturbed cells to compute a perturbation space and explore genetic interaction manifolds. Here, we successfully reproduced the results presented by Norman et al. (2019)<a href="https://www.science.org/doi/10.1126/science.aax4438)," target="_blank">,</a> as perturbations with the same pre-annotated gene programs cluster together in the pseudobulked perturbation space. Additionally, we extended the gene program annotation to perturbations with unannotated gene programs using label transfer. Overall, this analysis enables the exploration of how distinct perturbations target similar or different molecular mechanisms.</blockquote>

---

 <a href='https://app.reviewnb.com/scverse/pertpy-tutorials/pull/48/discussion/#comment-2379536636'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>The entire code cell is just there to obtain the reference cell type for the entire dataset, i.e. the adata which includes all treatments. I then create new Sccoda models for the adatas with individual treatments.</p>

---

 <a href='https://app.reviewnb.com/scverse/pertpy-tutorials/pull/48/discussion/#comment-2379536741'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>I changed the sentence to:</p><blockquote>We will then use the identified perturbed cells to compute a perturbation space and explore the genetic interaction manifolds, meaning we will explore how distinct perturbations target similar or different molecular mechanisms and how these effects can be visualized in a low-dimensional space.</blockquote>

---

 <a href='https://app.reviewnb.com/scverse/pertpy-tutorials/pull/48/discussion/#comment-2379536606'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>I renamed it to <code>subset_to_common_cell_types</code></p>

---

 <a href='https://app.reviewnb.com/scverse/pertpy-tutorials/pull/48/discussion/#comment-2379536677'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>I added:</p><blockquote>The heatmaps above show that patients who responded to chemotherapy showed a larger difference between their pre- and post-treatment expression profiles compared to those who responded to the combination of anti-PDL-1 and chemotherapy. This indicates that the combination therapy may have led to a less intense response or was applied in cases with poorer prognoses.</blockquote>

---

 <a href='https://app.reviewnb.com/scverse/pertpy-tutorials/pull/48/discussion/#comment-2379536709'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>I added:</p><blockquote>This fits to our earlier findings from the distance metric analysis, where we observed that the Anti-PD-L1 + Chemo group showed a smaller difference between their pre- and post-treatment expression profiles compared to the Chemo group. Overall, these findings indicate that the Anti-PD-L1 + Chemo combination therapy may have led to a less intense response or was applied in cases with poorer prognoses.</blockquote>

---

 <a href='https://app.reviewnb.com/scverse/pertpy-tutorials/pull/48/discussion/#comment-2379536765'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>I opened an issue (<a href="https://github.com/scverse/pertpy/issues/664" target="_blank">https://github.com/scverse/pertpy/issues/664</a>) because I think this requires a bit more discussion and possibly a general revision of the metadata UX.</p>

---

 <a href='https://app.reviewnb.com/scverse/pertpy-tutorials/pull/48/discussion/#comment-2379536495'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Lilly-May** [comment]
<p>I opened an issue (<a href="https://github.com/scverse/pertpy/issues/664" target="_blank">https://github.com/scverse/pertpy/issues/664</a>) for this because I think this requires a bit more discussion and possibly a general revision of the metadata UX.</p>

---

 <a href='https://app.reviewnb.com/scverse/pertpy-tutorials/pull/48/discussion/#comment-2379536548'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Zethson** [comment]
Thanks! Feel free to merge and pull then.

**Pull request merged**
